### PR TITLE
Che 32 most queens in game

### PR DESCRIPTION
**Pull request by bennyrubanov**
can remove the piecesOnBoardCount as it doesn't have a ton of value i think?

### CODE REVIEW

**Comment by EllAchE** [comment]
do you mind resolving merge conflicts on this one? Did it for your other PR

**Comment by bennyrubanov** [comment]
yep will resolve merge conflicts. thx for doing for the other

**Comment by bennyrubanov** [comment]
needs final review after merge conflicts resolution

**Review by EllAchE — APPROVED** [review]

**Review by EllAchE — CHANGES_REQUESTED** [review]
fix conflicts

**Pull request closed without merging**
